### ISSUE TITLE
Staging Site has no ability to Send Emails

### ISSUE THREAD

**Issue by d4mation** [realbig/PL_PYIS_ADDRESS_COLLECTION#5]
(This is after disabling the "Stop Emails" plugin, but since I'm testing PHP `mail()` here it shouldn't technically matter according to their documentation)

Reproduction Steps:
1. SSH into Server
2. `php -a`
3. `mail( 'you@example.com', "Test Postfix", "Test mail from postfix" );`

Returns: `/usr/sbin/sendmail: not found`

Can't test any e-mail functionality on the Staging Server as a result :/

**Comment by d4mation** [comment]
@jrosebr1 this is the only blocker we have right now. Everything else has been implemented and tested.

**Comment by jrosebr1** [comment]
As the name suggests, the "Stop Emails" plugin is used to prevent emails from being sent out. This is because the MemberPress plugin will send out reminder emails to users regarding failed payment. To get around this, the Stop Emails plugin simply prevents these emails.

I'll install and configure a mail system on the dev server to unblock this.

**Comment by d4mation** [comment]
I figured as much since it blocks `wp_mail()`. "Stop Emails" can stay active and I'll test using PHP `mail()` and switch it over to `wp_mail()` once everything is working for the final version 👍

**Comment by jrosebr1** [comment]
The dev server has now been configured to use postfix using my SendGrid credentials. I've tested that mail is being correctly sent via PHP's `mail` function. I've put an example of such a working `mail` call in `test_email.php` of the `dev` account. That should unblock this issue.

**Comment by d4mation** [comment]
Excellent! I'll get cracking at this
