### ISSUE TITLE
Add Second CongnitoForms URL, Another Tag, and Other Functionality

### ISSUE THREAD

**Issue by BigActual** [realbig/PL_PYIS_ADDRESS_COLLECTION#9]
Additionally, @jrosebr1 has a second physical book that I am shipping out. He needs this plugin to work with another CognitoForms URL and another tag.
Check with Adrian for additional functionality that needs to be added as well.

**Comment by d4mation** [comment]
@jrosebr1 

I have added support for this in the latest beta: https://github.com/Py-Image/PL_PYIS_ADDRESS_COLLECTION/releases/tag/v1.1.0b4

It utilizes the fact that the Form Name is sent along with the JSON data in order to know which Tags to check for to determine if it is a valid/suspicious entry and to know which Tags to add if they are valid/suspicious entries. 

The Password Field is no longer a Password Field in this beta, but it works the same way. I made an issue for this here: realbig/rbm-field-helpers#55

I can get that buttoned up for the release if you want. Otherwise, pending testing, this should be good!

**Comment by jrosebr1** [comment]
Thanks @d4mation 😄 I have installed the plugin and will monitor the results.

**Comment by d4mation** [comment]
All set! I fixed up the Password Field bit quickly as well. 

The way I am handling the Fields themselves now is via a Git Submodule, so the easiest way to ensure you download all the necessary files would be to click the first link.

https://github.com/Py-Image/PL_PYIS_ADDRESS_COLLECTION/releases/tag/v1.1.0
